### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by casperlehmann** [Haxonek/sample-epub-minimal#1]
The page linked in the readme is dead (https://haxonek.github.io/Building-an-epub-file/)

**Comment by bhubr** [comment]
Hello there!

It seems that the maintainer simply changed his GitHub login.

 The page can be found here: <https://thansen0.github.io/Building-an-epub-file/>.

**Comment by thansen0** [comment]
I'm sorry I guess I missed this; thanks for the catch, should be updated
